/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.10.0
 *
 * Project: 'AK_base_linux_port.Debug+SSE-320-FVP' 
 * Target:  'Debug+SSE-320-FVP' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "SSE320.h"

/* ARM::CMSIS Driver:USART@1.1.0 */
#define RTE_USART0      1
#define RTE_USART1      1

/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::Device:Native Driver:IO@1.0.1 */
#define RTE_MPS3_IO      1


#endif /* RTE_COMPONENTS_H */
